/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//Enable ADC and its clock configuration and GPIO clock
#define AHB1_ENR_ADDR  0x40023830UL
#define APB2_ENR_ADDR  0x40023844UL

//GPIOA Clock Enable Register
#define GPIO_ENR_ADDR  0x40020000UL

//choosing Mode for GPIO Register
#define GPIOA_MODER    0x40020000UL
//#define GPIOA_IDR      0x40020010UL
//#define GPIOx_ODR      0x40020014UL

//Address for AD1
#define  ADC1_ADDR     0x40012000UL

//Enable Address for the status register (Holds Status Flag)
#define ADC1_SR        0x40012000UL

//control Register for ADC1 .This not for enabling ADC
//#define ADC1_CR1       0x40012004UL

//control Register for ADC1.This is for Enabling ADC
#define ADC1_CR2       0x40012008UL

//ADC_SMPR2 for sampling the voltage
#define ADC1_SMPR2      0x40012010UL

//Regular Sequence Register 1 for Total number of conversions in the regular sequence.
#define  ADC1_SQR1       0x4001202CUL

#define ADC1_SQR3       0x40012034UL

#define ADC1_DR         0x4001204CUL
#define ADC_CCR         0x40012304UL

volatile uint16_t adc_value = 0;
int main(void)
{
	uint32_t *pAhb1EnrAddr =(uint32_t*)AHB1_ENR_ADDR;
	uint32_t *pApb2EnrAddr =(uint32_t*)APB2_ENR_ADDR;
	uint32_t *pGpioModer = (uint32_t*)GPIOA_MODER;
	uint32_t *pAdc1Sr    = (uint32_t*)ADC1_SR;
	uint32_t *pAdc1Cr2   = (uint32_t*)ADC1_CR2;
	uint32_t *pAdc1Smpr2 = (uint32_t*)ADC1_SMPR2; //ADC_SMPR2 → Channels 0–9
	uint32_t *pAdc1Sqr1  = (uint32_t*)ADC1_SQR1;
	uint32_t *pAdc1Sqr3  = (uint32_t*)ADC1_SQR3;
	uint32_t *pAdc1Dr   = (uint32_t*)ADC1_DR;
	uint32_t *pAdcCcr    = (uint32_t*)ADC_CCR;
    /* Loop forever */
	*pAhb1EnrAddr |= (1<<0); //GPIOA Clock Enable
	*pApb2EnrAddr |= (1<<8); //ADC1 Clock Enable

	*pGpioModer   |= (0x3<<0); //Set PA0 as Analog Mode
	*pAdcCcr      |= (0b01<<16); //ADC prescaler = Divided by 4
	*pAdc1Sqr1    &=~(0xF<<20); //Total Number of conversions in regular sequence
	*pAdc1Sqr3    |= 0; //First Conversion in regular sequence
	*pAdc1Smpr2   |= (1<<0); //sample time = 15 cycles
	*pAdc1Cr2     |= (1<<0); //Enable ADC
	*pAdc1Cr2     |= (1<<1); //Continuous conversion mode
	for(;;){
		*pAdc1Cr2 |= (1<<30); //Start of conversion
	while(!(*pAdc1Sr&(1<<1))); //This loop run until the ADC has finished converting a value and the result is ready to be read.”

    adc_value =*pAdc1Dr;

    for(volatile int i=0;i<10000;i++);
	}
}
